apiVersion: v1
kind: Service
metadata:
  name: techbrief-web
  namespace: techbrief
  labels:
    app.kubernetes.io/name: techbrief
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8010
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: techbrief
    app.kubernetes.io/component: web
