# Generated by Django 5.2.15 on 2026-06-05 06:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('stage', models.CharField(choices=[('discover', 'Discover'), ('fetch', 'Fetch'), ('extract', 'Extract'), ('transcribe', 'Transcribe'), ('translate', 'Translate'), ('research', 'Research'), ('review_pending', 'Review Pending'), ('publish', 'Publish'), ('notify', 'Notify')], max_length=32)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=32)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('admin_user', 'Admin User'), ('system_retry', 'System Retry'), ('system', 'System')], default='system', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('retryable', models.BooleanField(default=False)),
                ('context_json', models.JSONField(blank=True, null=True)),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='content_pipeline.contentitem')),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='content_pipeline.discoveryrun')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_run_log',
                'indexes': [models.Index(fields=['run_id'], name='tb_run_log_run_id_3015df_idx'), models.Index(fields=['content_item'], name='tb_run_log_content_669cec_idx'), models.Index(fields=['content_item', 'stage', 'status'], name='tb_run_log_content_f93346_idx'), models.Index(fields=['discovery_run'], name='tb_run_log_discove_f8848c_idx')],
            },
        ),
    ]
