# Generated by Django 5.2.15 on 2026-06-05 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name_snapshot', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('manual', 'Manual')], max_length=32)),
                ('ingestion_mode', models.CharField(choices=[('auto', 'Auto'), ('manual_url', 'Manual URL'), ('manual_rich_text', 'Manual Rich Text')], default='auto', max_length=32)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('processing', 'Processing'), ('review_pending', 'Review Pending'), ('published', 'Published'), ('failed', 'Failed'), ('archived', 'Archived')], default='discovered', max_length=32)),
                ('current_stage', models.CharField(choices=[('discover', 'Discover'), ('fetch', 'Fetch'), ('extract', 'Extract'), ('transcribe', 'Transcribe'), ('translate', 'Translate'), ('research', 'Research'), ('review_pending', 'Review Pending'), ('publish', 'Publish'), ('notify', 'Notify')], default='discover', max_length=32)),
                ('title_original', models.CharField(max_length=512)),
                ('title_zh', models.CharField(blank=True, max_length=512, null=True)),
                ('summary_original', models.TextField(blank=True, null=True)),
                ('summary_zh', models.TextField(blank=True, null=True)),
                ('author_or_speaker', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('final_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('source_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('published_at_source', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('original_language', models.CharField(default='en', max_length=16)),
                ('text_source_status', models.CharField(choices=[('html', 'HTML'), ('subtitle', 'Subtitle'), ('auto_subtitle', 'Auto Subtitle'), ('asr', 'ASR'), ('manual_input', 'Manual Input'), ('none', 'None')], default='none', max_length=32)),
                ('content_ast', models.JSONField(blank=True, null=True)),
                ('content_md', models.TextField(blank=True, null=True)),
                ('zh_ast', models.JSONField(blank=True, null=True)),
                ('zh_md', models.TextField(blank=True, null=True)),
                ('research_report_md', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('transcript_segments_json', models.JSONField(blank=True, null=True)),
                ('transcript_language', models.CharField(blank=True, max_length=16, null=True)),
                ('transcription_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('supports_bilingual', models.BooleanField(default=True)),
                ('web_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('published_at_web', models.DateTimeField(blank=True, null=True)),
                ('latest_run_id', models.UUIDField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('last_error_stage', models.CharField(blank=True, max_length=32, null=True)),
                ('timings_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_content_item',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('run_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('replay', 'Replay')], default='scheduled', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('partial_failed', 'Partial Failed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('admin_user', 'Admin User'), ('system_retry', 'System Retry'), ('system', 'System')], default='scheduler', max_length=32)),
                ('source_scope', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('enqueued_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_discovery_run',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRunSourceStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_discovery_run_source_stat',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_code', models.CharField(max_length=32, unique=True)),
                ('source_name', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('official_site', 'Official Site'), ('video_channel', 'Video Channel'), ('manual_external', 'Manual External')], default='official_site', max_length=32)),
                ('base_url', models.URLField(blank=True, max_length=512, null=True)),
                ('default_language', models.CharField(default='en', max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('schedule_cron_expr', models.CharField(default='0 2 * * *', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_source',
            },
        ),
        migrations.CreateModel(
            name='SourceEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint_type', models.CharField(choices=[('rss', 'RSS'), ('html_list', 'HTML List'), ('sitemap', 'Sitemap'), ('video_channel', 'Video Channel')], max_length=32)),
                ('endpoint_role', models.CharField(choices=[('primary', 'Primary'), ('fallback', 'Fallback'), ('supplemental', 'Supplemental')], default='primary', max_length=32)),
                ('endpoint_url', models.URLField(max_length=1024)),
                ('content_type_scope', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('mixed', 'Mixed')], default='mixed', max_length=32)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('parser_config', models.JSONField(blank=True, null=True)),
                ('last_etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_header', models.CharField(blank=True, max_length=255, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_source_endpoint',
            },
        ),
        migrations.CreateModel(
            name='ContentArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact_type', models.CharField(choices=[('raw_html', 'Raw HTML'), ('http_response', 'HTTP Response'), ('subtitle_manual', 'Subtitle Manual'), ('subtitle_auto', 'Subtitle Auto'), ('audio', 'Audio'), ('transcript_text', 'Transcript Text'), ('transcript_segments', 'Transcript Segments'), ('cover_image', 'Cover Image'), ('body_image', 'Body Image'), ('debug_file', 'Debug File'), ('wechat_html', 'WeChat HTML')], max_length=64)),
                ('storage_provider', models.CharField(default='tencent_cos', max_length=32)),
                ('bucket_name', models.CharField(max_length=128)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('content_type', models.CharField(max_length=128)),
                ('file_ext', models.CharField(blank=True, max_length=16, null=True)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='content_pipeline.contentitem')),
            ],
            options={
                'db_table': 'tb_content_artifact',
            },
        ),
    ]
