# Generated by Django 5.2.15 on 2026-06-05 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryrun',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discoveryrunsourcestat',
            name='discovery_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_stats', to='content_pipeline.discoveryrun'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_enabled'], name='tb_source_is_enab_b41388_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_enabled', 'schedule_cron_expr'], name='tb_source_is_enab_d39cb7_idx'),
        ),
        migrations.AddField(
            model_name='discoveryrunsourcestat',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_stats', to='content_pipeline.source'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='content_pipeline.source'),
        ),
        migrations.AddField(
            model_name='sourceendpoint',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='content_pipeline.source'),
        ),
        migrations.AddField(
            model_name='discoveryrunsourcestat',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_stats', to='content_pipeline.sourceendpoint'),
        ),
        migrations.AddIndex(
            model_name='contentartifact',
            index=models.Index(fields=['content_item'], name='tb_content__content_93956a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentartifact',
            index=models.Index(fields=['artifact_type'], name='tb_content__artifac_533ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='contentartifact',
            index=models.Index(fields=['content_item', 'artifact_type'], name='tb_content__content_45e2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveryrun',
            index=models.Index(fields=['status', 'started_at'], name='tb_discover_status_5d3236_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveryrun',
            index=models.Index(fields=['triggered_by_user'], name='tb_discover_trigger_cadfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['source', 'status'], name='tb_content__source__942636_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type', 'status', 'published_at_source'], name='tb_content__content_9cb436_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['canonical_url'], name='tb_content__canonic_ff5111_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['source_item_id'], name='tb_content__source__c1d3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['discovered_at'], name='tb_content__discove_162548_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceendpoint',
            index=models.Index(fields=['source'], name='tb_source_e_source__fc3255_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceendpoint',
            index=models.Index(fields=['is_enabled', 'priority'], name='tb_source_e_is_enab_8ef0f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceendpoint',
            constraint=models.UniqueConstraint(fields=('source', 'endpoint_url'), name='uk_tb_source_endpoint_source_url'),
        ),
        migrations.AddIndex(
            model_name='discoveryrunsourcestat',
            index=models.Index(fields=['discovery_run'], name='tb_discover_discove_4207ae_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveryrunsourcestat',
            index=models.Index(fields=['source'], name='tb_discover_source__b45298_idx'),
        ),
        migrations.AddConstraint(
            model_name='discoveryrunsourcestat',
            constraint=models.UniqueConstraint(condition=models.Q(('endpoint__isnull', False)), fields=('discovery_run', 'source', 'endpoint'), name='uk_tb_discovery_run_source_stat_scope_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='discoveryrunsourcestat',
            constraint=models.UniqueConstraint(condition=models.Q(('endpoint__isnull', True)), fields=('discovery_run', 'source'), name='uk_tb_discovery_run_source_stat_scope_source'),
        ),
    ]
