# Generated by Django 5.2.15 on 2026-06-05 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDigestBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial_failed', 'Partial Failed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('admin_user', 'Admin User'), ('system_retry', 'System Retry'), ('system', 'System')], default='scheduler', max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('total_content_count', models.PositiveIntegerField(default=0)),
                ('total_recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('provider_name', models.CharField(default='resend', max_length=32)),
                ('provider_batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_digest_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_email_digest_batch',
            },
        ),
        migrations.CreateModel(
            name='EmailDigestBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publishers.emaildigestbatch')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_items', to='content_pipeline.contentitem')),
            ],
            options={
                'db_table': 'tb_email_digest_batch_item',
            },
        ),
        migrations.CreateModel(
            name='PublishRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('wechat_draft', 'WeChat Draft'), ('email_digest', 'Email Digest')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('run_id', models.UUIDField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('admin_user', 'Admin User'), ('system_retry', 'System Retry'), ('system', 'System')], default='system', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, null=True)),
                ('response_snapshot', models.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_records', to='content_pipeline.contentitem')),
                ('email_digest_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_records', to='publishers.emaildigestbatch')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_publish_record',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='active', max_length=32)),
                ('source_page', models.CharField(choices=[('home_hero', 'Home Hero'), ('nav_modal', 'Nav Modal'), ('subscription_modal', 'Subscription Modal'), ('article_floating_cta', 'Article Floating CTA'), ('unknown', 'Unknown')], default='unknown', max_length=64)),
                ('locale', models.CharField(default='zh-CN', max_length=16)),
                ('unsubscribe_token', models.CharField(max_length=128, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_bounced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_subscriber',
                'indexes': [models.Index(fields=['status'], name='tb_subscrib_status_a38454_idx'), models.Index(fields=['subscribed_at'], name='tb_subscrib_subscri_e1f862_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='queued', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='publishers.emaildigestbatch')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='publishers.subscriber')),
            ],
            options={
                'db_table': 'tb_email_delivery',
            },
        ),
        migrations.CreateModel(
            name='WeChatDraftDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_mode', models.CharField(choices=[('content_item', 'Content Item'), ('manual_input', 'Manual Input')], max_length=32)),
                ('manual_title', models.CharField(blank=True, max_length=512, null=True)),
                ('manual_author', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_digest', models.TextField(blank=True, null=True)),
                ('thumb_media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('show_cover_pic', models.BooleanField(default=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('body_source_content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wechat_body_usages', to='content_pipeline.contentitem')),
                ('publish_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_detail', to='publishers.publishrecord')),
                ('wechat_html_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wechat_draft_details', to='content_pipeline.contentartifact')),
            ],
            options={
                'db_table': 'tb_wechat_draft_detail',
            },
        ),
        migrations.CreateModel(
            name='ContentPageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_kind', models.CharField(choices=[('article', 'Article'), ('video', 'Video')], max_length=32)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('source_name_snapshot', models.CharField(max_length=128)),
                ('title_original_snapshot', models.CharField(max_length=512)),
                ('title_zh_snapshot', models.CharField(max_length=512)),
                ('summary_zh_snapshot', models.TextField(blank=True, null=True)),
                ('body_original_md_snapshot', models.TextField(blank=True, null=True)),
                ('body_zh_md_snapshot', models.TextField()),
                ('author_or_speaker_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url_snapshot', models.URLField(max_length=1024)),
                ('canonical_url_snapshot', models.URLField(blank=True, max_length=1024, null=True)),
                ('published_at_source_snapshot', models.DateTimeField(blank=True, null=True)),
                ('supports_bilingual', models.BooleanField(default=True)),
                ('disclaimer_md_snapshot', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=512, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_snapshot', to='content_pipeline.contentitem')),
                ('cover_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_snapshots', to='content_pipeline.contentartifact')),
            ],
            options={
                'db_table': 'tb_content_page_snapshot',
                'indexes': [models.Index(fields=['page_kind', 'is_published'], name='tb_content__page_ki_0f9c2a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emaildigestbatch',
            index=models.Index(fields=['status'], name='tb_email_di_status_2515bd_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildigestbatchitem',
            index=models.Index(fields=['batch'], name='tb_email_di_batch_i_5a9be9_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildigestbatchitem',
            index=models.Index(fields=['content_item'], name='tb_email_di_content_b35b61_idx'),
        ),
        migrations.AddConstraint(
            model_name='emaildigestbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'content_item'), name='uk_tb_email_digest_batch_item_unique'),
        ),
        migrations.AddIndex(
            model_name='publishrecord',
            index=models.Index(fields=['content_item'], name='tb_publish__content_c20c13_idx'),
        ),
        migrations.AddIndex(
            model_name='publishrecord',
            index=models.Index(fields=['channel', 'status'], name='tb_publish__channel_14e62a_idx'),
        ),
        migrations.AddIndex(
            model_name='publishrecord',
            index=models.Index(fields=['external_id'], name='tb_publish__externa_76c613_idx'),
        ),
        migrations.AddIndex(
            model_name='publishrecord',
            index=models.Index(fields=['email_digest_batch'], name='tb_publish__email_d_66b4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['status'], name='tb_email_de_status_98920d_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['subscriber'], name='tb_email_de_subscri_6be590_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['provider_message_id'], name='tb_email_de_provide_5e15c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='emaildelivery',
            constraint=models.UniqueConstraint(fields=('batch', 'subscriber'), name='uk_tb_email_delivery_batch_subscriber'),
        ),
        migrations.AddIndex(
            model_name='wechatdraftdetail',
            index=models.Index(fields=['body_source_content_item'], name='tb_wechat_d_body_so_bbb445_idx'),
        ),
    ]
