# Generated by Django 5.2.15 on 2026-06-05 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_zh', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('page_code', models.CharField(choices=[('articles', 'Articles'), ('archive', 'Archive')], max_length=32, unique=True)),
                ('subtitle_zh', models.TextField(blank=True)),
                ('subtitle_en', models.TextField(blank=True)),
                ('default_sort', models.CharField(choices=[('published_desc', 'Published Desc'), ('published_asc', 'Published Asc'), ('updated_desc', 'Updated Desc')], default='published_desc', max_length=32)),
                ('default_filters_json', models.JSONField(blank=True, null=True)),
                ('enable_date_filter', models.BooleanField(default=True)),
                ('page_size', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Listing Page',
                'verbose_name_plural': 'Listing Pages',
                'db_table': 'tb_listing_page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_zh', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('page_code', models.CharField(choices=[('about', 'About'), ('privacy', 'Privacy'), ('terms', 'Terms')], max_length=32, unique=True)),
                ('body_md_zh', models.TextField()),
                ('body_md_en', models.TextField()),
                ('body_html_zh', models.TextField(blank=True)),
                ('body_html_en', models.TextField(blank=True)),
                ('seo_title_zh', models.CharField(blank=True, max_length=255)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_description_zh', models.CharField(blank=True, max_length=512)),
                ('seo_description_en', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'db_table': 'tb_static_page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_zh', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('hero_title_zh', models.CharField(max_length=255)),
                ('hero_title_en', models.CharField(max_length=255)),
                ('hero_subtitle_zh', models.TextField()),
                ('hero_subtitle_en', models.TextField()),
                ('subscribe_placeholder_zh', models.CharField(default='输入邮箱地址', max_length=128)),
                ('subscribe_placeholder_en', models.CharField(default='Enter your email', max_length=128)),
                ('primary_cta_text_zh', models.CharField(default='立即订阅', max_length=64)),
                ('primary_cta_text_en', models.CharField(default='Subscribe', max_length=64)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
                'db_table': 'tb_home_page',
                'indexes': [models.Index(fields=['is_published'], name='idx_tb_home_page_is_published')],
            },
            bases=('wagtailcore.page',),
        ),
    ]
